// Plate Ledger — Phase 1 temporary test harness.
// There's no real Add/Edit UI yet (that's Phase 2) or map pins (Phase 3), so
// this bare panel exercises create/read/update/delete and export/import
// directly against js/db.js to confirm the storage layer on-device.
// Delete this file (and its wiring in index.html) once Phase 2 ships.

(function () {
  "use strict";

  var SAMPLE_NAMES = ["Mesa Verde", "Blue Heron Diner", "Nonna's Table", "The Rusty Fork", "Sakura House"];
  var SAMPLE_TOWNS = ["Ashland", "Rivertown", "Millbrook", "Cedar Falls"];

  function sampleFields() {
    var isBeen = Math.random() < 0.5;
    var name = SAMPLE_NAMES[Math.floor(Math.random() * SAMPLE_NAMES.length)] + " " + Math.floor(Math.random() * 100);
    var town = SAMPLE_TOWNS[Math.floor(Math.random() * SAMPLE_TOWNS.length)];
    var fields = {
      name: name,
      address: "123 Main St, " + town,
      town: town,
      status: isBeen ? PlateLedgerDB.STATUS.BEEN : PlateLedgerDB.STATUS.WANT_TO_GO,
      recommendedBy: "test data",
      notes: "Sample record generated by the Phase 1 debug panel.",
    };
    if (isBeen) {
      Object.assign(fields, {
        rating: 1 + Math.floor(Math.random() * 5),
        priceRange: PlateLedgerDB.PRICE_RANGES[Math.floor(Math.random() * PlateLedgerDB.PRICE_RANGES.length)],
        nonChain: Math.random() < 0.7,
        serviceStyle: PlateLedgerDB.SERVICE_STYLES[Math.floor(Math.random() * PlateLedgerDB.SERVICE_STYLES.length)],
        cuisines: [PlateLedgerDB.CUISINES[Math.floor(Math.random() * PlateLedgerDB.CUISINES.length)]],
        mealsHad: "Something off the menu",
        goodDateSpot: Math.random() < 0.5,
        lastVisited: new Date().toISOString().slice(0, 10),
        wouldGoAgain: Math.random() < 0.8,
        goodForGroups: Math.random() < 0.5,
        outdoorSeating: Math.random() < 0.5,
        reservations: PlateLedgerDB.RESERVATIONS_OPTIONS[Math.floor(Math.random() * PlateLedgerDB.RESERVATIONS_OPTIONS.length)],
        dietaryTags: [PlateLedgerDB.DIETARY_TAGS[Math.floor(Math.random() * PlateLedgerDB.DIETARY_TAGS.length)]],
        noiseLevel: PlateLedgerDB.NOISE_LEVELS[Math.floor(Math.random() * PlateLedgerDB.NOISE_LEVELS.length)],
        websiteUrl: "https://example.com",
      });
    }
    return fields;
  }

  function el(tag, attrs, children) {
    var node = document.createElement(tag);
    Object.keys(attrs || {}).forEach(function (k) {
      if (k === "text") node.textContent = attrs[k];
      else node.setAttribute(k, attrs[k]);
    });
    (children || []).forEach(function (c) {
      node.appendChild(c);
    });
    return node;
  }

  function refreshList() {
    var listEl = document.getElementById("debug-list");
    var countEl = document.getElementById("debug-count");
    listEl.innerHTML = "";
    PlateLedgerDB.getAllRestaurants().then(function (restaurants) {
      restaurants.sort(function (a, b) {
        return (b.dateAdded || "").localeCompare(a.dateAdded || "");
      });
      countEl.textContent = restaurants.length + " record(s)";
      restaurants.forEach(function (r) {
        var statusLabel = r.status === PlateLedgerDB.STATUS.BEEN ? "Been" : "Want to Go";
        var label = el("span", {
          text: r.name + " — " + statusLabel + (r.town ? " (" + r.town + ")" : "") + (r.rating ? " ★" + r.rating : ""),
        });
        var toggleBtn = el("button", { text: "Toggle status" });
        toggleBtn.onclick = function () {
          var newStatus = r.status === PlateLedgerDB.STATUS.BEEN ? PlateLedgerDB.STATUS.WANT_TO_GO : PlateLedgerDB.STATUS.BEEN;
          PlateLedgerDB.updateRestaurant(r.id, { status: newStatus }).then(refreshList);
        };
        var deleteBtn = el("button", { text: "Delete" });
        deleteBtn.onclick = function () {
          PlateLedgerDB.deleteRestaurant(r.id).then(refreshList);
        };
        var row = el("div", { class: "debug-row" }, [label, toggleBtn, deleteBtn]);
        listEl.appendChild(row);
      });
    });
  }

  function downloadJSON(data, filename) {
    var blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
    var url = URL.createObjectURL(blob);
    var a = el("a", { href: url, download: filename });
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function buildPanel() {
    var toggle = el("button", { id: "debug-toggle", text: "Debug" });
    var panel = el("div", { id: "debug-panel" });
    panel.style.display = "none";

    var addBtn = el("button", { text: "+ Add test restaurant" });
    addBtn.onclick = function () {
      PlateLedgerDB.addRestaurant(sampleFields()).then(refreshList);
    };

    var exportBtn = el("button", { text: "Export JSON" });
    exportBtn.onclick = function () {
      PlateLedgerDB.exportAll().then(function (data) {
        downloadJSON(data, "plate-ledger-export-" + Date.now() + ".json");
      });
    };

    var importInput = el("input", { type: "file", accept: "application/json", id: "debug-import-input" });
    importInput.style.display = "none";
    importInput.onchange = function (e) {
      var file = e.target.files[0];
      if (!file) return;
      var reader = new FileReader();
      reader.onload = function () {
        try {
          var data = JSON.parse(reader.result);
          PlateLedgerDB.importAll(data, "merge").then(function (summary) {
            alert("Imported " + summary.imported + ", skipped " + summary.skipped);
            refreshList();
          });
        } catch (err) {
          alert("Import failed: " + err.message);
        }
      };
      reader.readAsText(file);
      importInput.value = "";
    };
    var importBtn = el("button", { text: "Import JSON" });
    importBtn.onclick = function () {
      importInput.click();
    };

    var clearBtn = el("button", { text: "Delete all", class: "debug-danger" });
    clearBtn.onclick = function () {
      if (confirm("Delete all restaurants from storage?")) {
        PlateLedgerDB.deleteAllRestaurants().then(refreshList);
      }
    };

    var controls = el("div", { id: "debug-controls" }, [addBtn, exportBtn, importBtn, clearBtn, importInput]);
    var count = el("div", { id: "debug-count" });
    var list = el("div", { id: "debug-list" });

    panel.appendChild(controls);
    panel.appendChild(count);
    panel.appendChild(list);

    toggle.onclick = function () {
      var open = panel.style.display !== "none";
      panel.style.display = open ? "none" : "block";
      if (!open) refreshList();
    };

    document.body.appendChild(toggle);
    document.body.appendChild(panel);
  }

  document.addEventListener("DOMContentLoaded", buildPanel);
})();
